// Auto-generated by tools/generate-insights.mjs. Do not edit by hand.
// Rerun after editing data.js: node tools/generate-insights.mjs
window.DASHBOARD_INSIGHTS = {
  "generatedAt": "2026-07-01T19:51:26.690Z",
  "model": "gpt-4o",
  "signature": "2aa7383d",
  "summary": "Overall, Acme Co is performing well with revenue and cash position exceeding targets. The biggest win is the strong cash position at $262,000. The biggest risk is the high A/R Days at 35 days, which is above the target of 30 days.",
  "pillars": {
    "Marketing": "Marketing metrics are generally positive with leads and cost per lead exceeding targets. Traffic is the weakest metric, missing the target of 40,000. Focus on increasing traffic to improve MQLs.",
    "Sales": "Sales metrics show improvement, but all are slightly below targets. Conversion rate is the weakest at 24.0% against a 25.0% target. Enhance sales strategies to boost conversion rates.",
    "Operations": "Operations face challenges with fulfillment time and churn both in red status. Fulfillment time is the weakest at 4 days against a 3-day target. Streamline processes to reduce fulfillment time.",
    "Finance": "Finance metrics are stable with a strong cash position and cash runway. A/R Days is the weakest metric at 35 days, above the target of 30 days. Improve collections to reduce A/R Days."
  }
};
